# Generated by Django 4.2.8 on 2026-08-26 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('project_type', models.CharField(choices=[('Odoo', 'Odoo'), ('Python', 'Python'), ('Django', 'Django'), ('Flask', 'Flask'), ('API / Integration', 'API / Integration'), ('KI / Chatbot', 'KI / Chatbot'), ('Automatisierung', 'Automatisierung'), ('Digitalisierung', 'Digitalisierung'), ('Andere', 'Andere')], default='Odoo', max_length=50)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
