services:
  - type: web
    name: adib-portfolio-backend
    runtime: python
    pythonVersion: 3.10
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd backend && gunicorn config.wsgi:application --workers 4 --bind 0.0.0.0:8000"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DEBUG
        value: "false"
