# Generated by Django 4.2.14 on 2026-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service_type', models.CharField(choices=[('django', 'Django & Flask Development'), ('odoo', 'Odoo ERP Solutions'), ('ai', 'AI & Chatbot Engineering'), ('other', 'Sonstiges / Other')], max_length=20)),
                ('budget', models.CharField(blank=True, choices=[('< 2000', '< 2.000 €'), ('2000-5000', '2.000 - 5.000 €'), ('5000-10000', '5.000 - 10.000 €'), ('10000+', '> 10.000 €')], max_length=50, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
