# Generated by Django 4.2.14 on 2026-08-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_email_sent_emaillog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Email Logs'},
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='portfolio_e_status_b91dc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='emaillog',
            name='portfolio_e_recipie_c2d13b_idx',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='last_retry',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Versendet'), ('failed', 'Fehlgeschlagen')], max_length=20),
        ),
    ]
